trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '10.x'

- script: dotnet restore
  displayName: 'Restore'

- script: dotnet build --configuration Release --no-restore
  displayName: 'Build'

- script: dotnet test --configuration Release --no-build
  displayName: 'Test'

